### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by leeper** [JakeRuss/bjs2r#1]
Great to see you working on this! I might suggest a name change, though. [JSTOR](http://en.wikipedia.org/wiki/JSTOR) is a prominent journal repository, and thus the current name here might cause confusion.

**Comment by JakeRuss** [comment]
I did notice that it worked out that way. I'm not married to any particular name, but nothing else obvious jumps out at me. I could take the 'to' part out and make it "bjsr" as that's not on CRAN. If you have a better suggestion, I'll be happy to use it.

The one thing I was trying to achieve with the name was to keep it generally applicable to BJS rather than solely the NCVS. Right now, I plan to call the NCVS function "get_ncvs", but if there are other BJS web services we can keep them all under the same BJS package umbrella.

**Comment by leeper** [comment]
I think keeping it general is a good idea. Some possible alternatives:
- bjsR
- bjs2R
- justice
- justats
- justicestatistics
- rjustice

**Comment by JakeRuss** [comment]
Doh! I hadn't considered swapping out 'to' for '2'. That should have been obvious, thank you! I'm leaning toward `bjs2r` or `BJS2R` as I'd like to avoid using mixed case.

**Comment by leeper** [comment]
Yes, that's a pretty common approach (e.g., http://cran.r-project.org/web/packages/git2r/index.html).

**Comment by JakeRuss** [comment]
Great, `bjs2r` it is then. Thanks!
